title: MCCE4 Tutorial
description: MCCE4 Tutorial Page - Jeykll site using the Just the Docs theme!
theme: just-the-docs
url: "https://GunnerLab.github.io"   # domain only
baseurl: "/mcce4_tutorial"           # repo name, leading slash

# Built-in search (optional)
color_scheme: light
search_enabled: true
nav_sort: case_insensitive

# Relative Links
markdown: kramdown
kramdown:
  input: GFM
permalink: pretty

defaults:
  - scope:
      path: "docs" 
      type: "pages"
    values:
      layout: "default"

# Footer: "Edit this page on GitHub" link text
gh_edit_link: true                                                # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"                     # Footer Text        
gh_edit_repository: "https://github.com/GunnerLab/mcce4_tutorial" # Github URL for your repo
gh_edit_branch: "main"                                            # Branch that your docs is served from
# gh_edit_source: docs                                            # Source that your files originate from
gh_edit_view_mode: "tree"                                         # Set "tree" or "edit" if you want the user to jump into the editor immediately


# Callouts
callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: üìå Important
    color: blue
  note:
    title: üìù Note
    color: purple
  warning:
    title: ‚ö†Ô∏è Warning
    color: red
  new:
    title: New
    color: green
