title: MCCE4 Tutorial
description: MCCE4 Tutorial Page - Jeykll site using the Just the Docs theme!
theme: just-the-docs
url: "https://GunnerLab.github.io"   # domain only
baseurl: "/mcce4_tutorial"           # repo name, leading slash

# Built-in search (optional)
color_scheme: light
search_enabled: true
nav_sort: case_insensitive

# Relative Links
markdown: kramdown
kramdown:
  input: GFM

permalink: pretty

defaults:
  - scope:
      path: "docs" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"

# GitHub edit links
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/GunnerLab/mcce4_tutorial"
gh_edit_branch: "main"
gh_edit_source: "docs"
gh_edit_view_mode: "edit"

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: üìå Important
    color: blue
  note:
    title: üìù Note
    color: purple
  warning:
    title: ‚ö†Ô∏è Warning
    color: red
  new:
    title: New
    color: green
